cb1:
  type: "CAPAROC"

  environment:
    SYS: "XF:31ID1-ES"
    DEV: "{CB:1}"
    HOST: 10.69.58.102
    CB_ASYNPORT: "CB1"
    PREFIX: "XF:31ID1-CT{IOC:CB1}"
    ENGINEER: "H. Xu"

    operations:
      - PORT_NAME: "${CB_ASYNPORT}_ERR_RST"
        MODBUS_FUNC: 16
        START_ADDR: 272
        MODBUS_LEN: 4
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_ERR_CNT_RST"
        MODBUS_FUNC: 16
        START_ADDR: 288
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_MOD_NUM"
        MODBUS_FUNC: 3
        START_ADDR: 8192
        MODBUS_LEN: 1
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_CHAN_NUM"
        MODBUS_FUNC: 3
        START_ADDR: 8193
        MODBUS_LEN: 4
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_MIN_NOM_I"
        MODBUS_FUNC: 3
        START_ADDR: 8224
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_MAX_NOM_I"
        MODBUS_FUNC: 3
        START_ADDR: 8288
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_GLB_STS"
        MODBUS_FUNC: 3
        START_ADDR: 24576
        MODBUS_LEN: 1
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_SYS_INP1"
        MODBUS_FUNC: 3
        START_ADDR: 24577
        MODBUS_LEN: 2
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_SYS_INP2"
        MODBUS_FUNC: 3
        START_ADDR: 24581
        MODBUS_LEN: 5
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_CHAN_STS"
        MODBUS_FUNC: 3
        START_ADDR: 24592
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_I_LOAD"
        MODBUS_FUNC: 3
        START_ADDR: 24656
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_ERR_CNT"
        MODBUS_FUNC: 3
        START_ADDR: 24720
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_CTRL_CHAN_STS"
        MODBUS_FUNC: 3
        START_ADDR: 49168
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_CTRL_CHAN_CMD"
        MODBUS_FUNC: 16
        START_ADDR: 49168
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_NOM_I_RB"
        MODBUS_FUNC: 3
        START_ADDR: 49232
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_NOM_I_SP"
        MODBUS_FUNC: 16
        START_ADDR: 49232
        MODBUS_LEN: 13
        DATA_TYPE: "UINT16"
      - PORT_NAME: "${CB_ASYNPORT}_MOD_NAME"
        MODBUS_FUNC: 3
        START_ADDR: 4096
        MODBUS_LEN: 80
        DATA_TYPE: "STRING_HIGH_LOW"
      

